(async () => {
  const prompts = [
    'A jade palace nestled within mist-shrouded peaks',
'A moonlit desert oasis ringed by glowing cacti',
'A crystalline ice cavern illuminated by falling snowflakes',
'A neon dragon winding through futuristic city streets',
'A hidden waterfall spilling into an emerald grotto',
'A pair of star-crossed lovers meeting under a bioluminescent tree',
'A sprawling sky-farm floating above cotton-candy clouds',
'A lone wanderer standing before an ancient rune-covered monolith',
'A lantern-lit bridge arching over a tranquil koi pond at dusk',
'A convoy of steam-powered airships cruising through violet skies',
'A secret moon garden carpeted in luminescent orchids',
'A regal monarch seated on a throne carved from starlight',
'A cloaked figure exploring a frost-bitten alien wasteland',
'A hidden tea pavilion nestled in a golden bamboo forest',
'A futuristic skyline reflected on rippling mercury pools',
'A drifting island crowned by a ring of floating lanterns',
'A pair of children chasing glowing moths in a nighttime meadow',
'A celestial cathedral carved into a drifting asteroid',
'A fisherman casting nets on a neon-lit cyber-river',
'A night market alive with holographic koi fish swimways',
'A secret canyon where crystals sprout like flowers',
'A mystical weeping willow glowing under a sapphire moon',
'A samurai ghost guarding an abandoned temple gate',
'A secret observatory perched atop a spiraling tower',
'A caravan of sky-nomads crossing an endless sunset plain',
'A sacred lotus blooming on a mirrored mountain lake',
'A serene cloister surrounded by drifting cherry petals',
'A neon-lit gondola gliding through cyberpunk canals',
'A dragon’s skull half-buried in a moonlit dune',
'A pair of explorers gazing at a twin-sun horizon',
'A floating sculpture garden above a sea of clouds',
'A lighthouse of light beaming across a storm-tossed sea',
'A hidden subterranean city lit by glowing quartz veins',
'A futuristic monorail slicing through misty rain forests',
'A secret waterfall glowing with biolumescent algae',
'A pair of monks meditating beside a glowing lotus pond',
'A neon-drenched alley where paper cranes flutter',
'A canyon of towering mushrooms under an emerald sky',
'A royal court held in a crystal hall of mirrors',
'A lone knight approaching a castle made of ice shards',
'A floating harbor of lantern-lit ships at dawn',
'A couple dancing on a glass bridge above a canyon of stars',
'A hidden lagoon beneath a ring of silver stalactites',
'A bioluminescent reef winding through coral towers',
'A futuristic palace carved from black obsidian',
'A pair of children floating on lily pads beneath lanterns',
'A sacred grove where trees bloom with light',
'A convoy of mech walkers crossing an ochre wasteland',
'A royal festival held beneath glowing jellyfish clouds',
'A moonlit stone circle surrounded by milky-white mist',
'A neon-lit tea shop tucked into an overgrown alley',
'A hidden valley of crystalline blossoms at sunrise',
'A dragon carved into living vines curling around a tower',
'A floating zen garden with drifting sakura petals',
'A lone alchemist’s workshop perched on a cliff edge',
'A city of glass spires glowing under an aurora borealis',
'A secret waterfall cascading onto glowing mossy rocks',
'A pair of lovers rowing through a lantern-lit canal',
'A futuristic skybridge crisscrossing neon skyscrapers',
'A hidden moon temple nestled in a crater lake',
'A convoy of glowing hovercraft racing across acid sands',
'A pair of sisters wandering through a snow-covered pavilion',
'A secret library of floating scrolls in a glass dome',
'A serene mountain path lined with glowing lanterns',
'A neon-drenched bazaar in a canyon of cliffs',
'A hidden oasis of luminous stones in a desert cavern',
'A sacred pyramid enveloped in drifting stardust',
'A royal procession across a bridge of light',
'A floating amphitheater above a sea of mist',
'A pair of adventurers entering a dragon’s maw cave',
'A neon cyber-forest where data streams through trees',
'A hidden tea house built around a giant bonsai',
'A convoy of sky whales swimming through cotton skies',
'A palace of ice floating on a crimson lagoon',
'A pair of monks carrying lanterns through snowy pines',
'A secret grotto illuminated by glowing beetles',
'A futuristic monolith rising from a glassy sea',
'A hidden canyon where rivers flow with liquid gold',
'A dragon-shaped mountain reflecting in a mirror lake',
'A floating cathedral draped in living vines',
'A convoy of traders on neon hover-bikes at dawn',
'A pair of children discovering a mirror-covered shrine',
'A secret garden of glass flowers beneath a pastel sky',
'A samurai duel on a floating platform of ice',
'A neon-lit ferry gliding through a cyberpunk harbor',
'A hidden waterfall spilling into a crater of crystals',
'A sacred lotus maze floating on a lavender pond',
'A pair of admirals meeting on a sky-battle deck',
'A secret moonlit trail of glowing mushrooms',
'A futuristic city built on concentric floating rings',
'A royal banquet held under a canopy of lanterns',
'A hidden waterfall cascading into a hall of mirrors',
'A lone mage summoning stars in a misty valley',
'A pair of siblings chasing fireflies through ruins',
'A neon dragon spiral wrapping around a tower block',
'A floating platform supporting a garden of glass trees',
'A hidden ice palace beneath a tapestry of auroras',
'A convoy of explorers navigating neon canyons',
'A pair of lovers meeting at a crystalline archway',
'A moonlit lavender field with drifting lanterns',
'A secret monastery perched on a pillar of stone',
'A futuristic skyline crowned by a giant lotus orb',
'A royal equestrian parade across glowing sands',
'A hidden tea pavilion on an emerald cliff face',
'A pair of monks releasing sky-lanterns at midnight',
'A dragon carved from living ice flying over a city',
'A neon-lit waterfall cascading down chrome rocks',
'A hidden canyon of glowing basalt columns',
'A celestial ascension platform floating above clouds',
'A pair of travelers camping under a bioluminescent tree',
'A neon-drenched hover taxi gliding past spired towers',
'A hidden oasis of floating lily pads on a glass sea',
'A secret temple illuminated by constellations on the floor',
'A pair of children sailing in paper boats on lantern streams',
'A futuristic monolith rising from an ocean of neon mist',
'A floating zen waterfall cascading into a reflective pool',
'A secret canyon where bioluminescent vines glow',
'A convoy of skyships docking at a crystal archipelago',
'A lone sentinel standing on a floating shard of obsidian',
'A royal procession under a glowing lotus sky',
'A hidden moonlit garden of phosphorescent peonies',
'A neon-lit gondola weaving through digital canals',
'A pair of explorers finding an ice-covered obelisk',
'A secret waterfall plunging into a mirrored abyss',
'A dragon’s silhouette against a neon cyber-skyline',
'A floating palace ringed by drifting lotus blossoms',
'A pair of lovers exchanging lanterns on a glass pier',
'A hidden glacier cave with walls of living crystal',
'A futuristic caravan crossing a desert of light trails',
'A secret courtyard where stones float in midair',
'A pair of children discovering a garden of holographic blooms',
'A neon canyon where data waterfalls sparkle',
'A drifting fortress carved into a living cloud',
'A royal scribe writing by lantern light in a silent hall',
'A hidden valley of glowing dragonscale plants',
'A futuristic skyline seen through a rain-smeared viewport',
'A pair of monks whispering in a heliotrope lotus pond',
'A neon-lit spiderweb bridge spanning two chrome towers',
'A dragon perched atop a floating magma rock',
'A secret moss-covered temple in a midnight forest',
'A convoy of robotic walkers crossing an emerald swamp',
'A pair of lovers reunited under a glowing archway',
'A hidden grotto where stalactites drip liquid starlight',
'A futuristic palace of shifting holographic walls',
'A secret moonlit labyrinth of reflective hedges',
'A pair of children chasing digital koi in a neon pond',
'A floating glass cube containing a miniature forest',
'A dragon spiraling around a crystalline spire at dawn',
'A royal throne room carved into a living tree',
'A hidden waterfall echoing through a glass canyon',
'A neon-drenched monorail station on a sky-island',
'A pair of adventurers gazing at an alien sunrise',
'A secret temple built around a giant luminous seed',
'A convoy of explorers entering a nebula-lit gorge',
'A dragon’s lair hidden in floating obsidian shards',
'A pair of lovers dancing in lantern rain at dusk',
'A hidden zen garden of swirling sand patterns',
'A futuristic sky-harbor bristling with hovercraft',
'A secret moonlit tower rising from a glass sea',
'A pair of monks chanting beside a glowing waterfall',
'A neon-lit cliffside tea house overlooking a city',
'A dragon’s wing casting shadow over a neon plaza',
'A convoy of sky caravans crossing amber clouds',
'A pair of children exploring a hidden lotus bloom',
'A secret glade where stars rain like petals',
'A futuristic arcology of spiraling glass domes',
'A royal eagle circling a floating citadel at dawn',
'A pair of lovers parting on a lantern-lined bridge',
'A hidden cavern of glowing amethyst stalagmites',
'A neon-drenched crossroads in a cyber jungle',
'A dragon woven from light flying above ruins',
'A hidden temple of shifting water illusions',
'A convoy of crystalline tanks rolling through neon streets',
'A lone bard playing a luminous lyre atop a spire',
'A pair of explorers entering a violet-hued canyon',
'A secret fountain where water flows upwards',
'A futuristic lighthouse of pure holographic beams',
'A dragon coiled around a floating obsidian palace',
'A hidden courtyard of levitating lotus petals',
'A pair of monks releasing bioluminescent frogs',
'A neon-lit sky-train speeding past glowing cliffs',
'A secret egg-shaped monastery on an ice floe',
'A convoy of starseed pods drifting through violet skies',
'A pair of siblings crafting lanterns in moonlight',
'A hidden alcove where crystals hum with energy',
'A futuristic coliseum powered by neon circuits',
'A dragon soaring through a ring of auroras',
'A pair of lovers meeting at the edge of a mirrored abyss',
'A secret canal where water glows like liquid glass',
'A royal envoy traveling on sky whales at dawn',
'A hidden grove where flowers drift on water',
'A neon-lit observatory atop a digital lotus',
'A pair of children reading glowing scrolls in a temple',
'A dragon’s shadow crossing a neon cityscape',
'A secret monolith rising in a field of lotus vines',
'A futuristic pack of hover-dogs racing at sunset',
'A pair of monks finding solace in a hidden pond',
'A neon-drenched market on the edge of a cliff',
'A dragon-shaped arch of glowing embers at dusk',
'A hidden path lined with floating jade stones',
'A convoy of lantern-lit sleds across crystal fields',
'A pair of lovers carving runes on a glowing tree',
'A futuristic palace of shifting light prisms',
'A secret cave where stalactites drip with moonlight',
'A dragon curled around a luminous moon gate',
'A pair of children discovering a field of light lilies',
'A neon-lit skybridge wrapped in drifting fog',
'A secret courtyard where shadows form living shapes',
'A convoy of sky-pigs grazing on cloud pastures',
'A pair of siblings whispering in a lantern orchard',
'A hidden pond reflecting a kaleidoscopic sky',
'A futuristic temple floating above a sea of data',
'A dragon’s roar echoing across neon canyons',
'A pair of lovers exchanging vows under lantern rain',
'A secret grotto where glowing lotus petals float',
'A convoy of luminescent jellyfish drifting through skies',
'A pair of monks seeking wisdom in a hidden archive',
'A neon-drenched shrine built into a canyon wall',
'A dragon perched on a floating obsidian lotus',
'A secret waterfall flowing through a mirrored palace',
'A futuristic skyline where towers bloom like flowers',
'A pair of children chasing drifting star petals',
'A hidden path where lanterns light themselves',
'A convoy of crystal caravans rolling across neon sands',
'A pair of lovers carving their names into light trees',
'A dragon spiraling through a field of holographic grass',
'A secret moon garden of floating glass blossoms',
'A futuristic cathedral of data streams and light',
'A pair of monks painting constellations on temple walls',
'A neon-lit rooftop garden overlooking a glass city',
'A dragon’s silhouette etched against a ringed planet',
'A hidden bazaar where lanterns sell memories',
'A convoy of sky-sailors navigating cloud currents',
'A pair of siblings finding a glowing lotus crown',
'A secret cavern where echoes form spectral shapes',
'A futuristic palace powered by neon vines',
'A dragon coiled around a silver observatory dome',
'A pair of lovers leaving lanterns on a glass pier',
'A hidden forest of glowing bamboo spires',
'A convoy of data-beetles crawling across neon circuits',
'A pair of monks carving lantern runes on stone steps',
'A neon-drenched rotunda floating on misty waters',
'A dragon’s heart glowing within a crystal cave',
'A secret courtyard where lotus petals whisper secrets',
'A futuristic skyline built atop floating flower terraces',
'A pair of children releasing glass fireflies at dusk',
'A hidden alley where streetlights bloom like flowers',
'A convoy of sky-trains weaving through neon canyons',
'A pair of lovers parting on a lantern-lined stairway',
'A secret zen pavilion perched on a drifting reef',
'A dragon carved from liquid starlight soaring high',
'A futuristic observatory encased in glowing vines',
'A pair of monks drinking tea in a moonlit courtyard',
'A neon-drenched garden of floating data blooms',
'A dragon’s lair hidden beneath a field of lanterns',
'A hidden grotto where water dances in light ribbons',
'A futuristic skyline reflected in a dripping chrome pool',
'A pair of children discovering a glowing rune stone',
'A secret bridge where footsteps leave trails of light',
'A convoy of sky-ducks migrating through neon skies',
'A pair of lovers carving dreams onto floating stones',
'A neon-lit observatory where stars descend to listen',
'A dragon’s roar carving ripples in a mirrored lake',
'A hidden grotto where lantern fish swim through air',
'A futuristic skyline woven from glowing vines',
'A pair of monks mapping the pattern of drifting lanterns',
'A secret zen pavilion rising on a lotus-shaped islet',
'A dragon clutching a neon-glowing heart above ruins',
'A hidden moonlit orchard of crystal apples',
'A futuristic bazaar floating on a sea of mist',
'A pair of children writing wishes on glowing petals',
'A secret canyon where stars drip like lava',
'A convoy of sky-serpents weaving through neon arches',
'A pair of siblings planting lantern seeds in silent soil',
'A neon-lit temple where shadows dance as light',
'A dragon’s silhouette curling around a glass spire',
'A hidden courtyard where moss glows like embers',
'A futuristic palace afloat on drifting data streams',
'A pair of monks releasing glowing lanterns into a void',
  ];
  const input     = document.querySelectorAll('.paragraph-input')[1];
  const genButton = document.querySelectorAll('#generateButtonEl')[0];

  // small helper to pause
  const wait = ms => new Promise(res => setTimeout(res, ms));

  for (let idx = 0; idx < prompts.length; idx++) {
    // 1) insert prompt + fire input event
    input.value = prompts[idx];
    input.dispatchEvent(new Event('input', { bubbles: true }));
    console.log(`🖊 Prompt #${idx+1}: ${prompts[idx]}`);

    // 2) click generate
    genButton.click();
    console.log('▶️ Generation started…');

    // 3) wait for generation to complete
    //    adjust this to cover your actual render time
    await wait(2 * 60_000);  
    console.log('⏳ Assuming generation done, saving…');

    // 4) click each save button, dismiss popup
    const buttons = Array.from(document.querySelectorAll('.private-save-button'));
    for (let i = 0; i < buttons.length; i++) {
      const btn = buttons[i];
      btn.click();
      console.log(`💾 Clicked save #${i+1}`);

      // 5) wait a bit for the “please wait…” dialog to show
      await wait(500);

      // 6) dispatch an “Enter” keydown to close it
      document.dispatchEvent(new KeyboardEvent('keydown', {
        key: 'Enter',
        code: 'Enter',
        bubbles: true,
      }));
      console.log('⏎ Dismissed popup');

      // 7) little breathing room before next
      await wait(300);
    }

    console.log(`✅ Completed prompt #${idx+1}`);
  }

  console.log('🎉 All prompts done!');
})();
